# Generated by Django 5.2.4 on 2025-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_department_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigened_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priraty',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
